name: psp_torch16
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - async_generator=1.10=py36h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blosc=1.20.1=hd408876_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.14.12=h8948797_3
  - certifi=2021.5.30=py36h06a4308_0
  - charls=2.1.0=he6710b0_2
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cudatoolkit=9.2=0
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - imagecodecs=2020.5.30=py36hfa7d478_2
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.0=pyhd3eb1b0_1
  - jedi=0.17.2=py36h06a4308_1
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.0=py36h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.3.1=py36h2531618_0
  - lcms2=2.11=h396b838_0
  - libaec=1.0.4=he6710b0_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib-base=3.2.1=py36hef1b27d_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - networkx=2.5.1=pyhd3eb1b0_0
  - ninja=1.10.0=hc9558a2_0
  - notebook=6.0.3=py36_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandas=1.1.5=py36ha9443f7_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py36h06a4308_1
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycairo=1.19.1=py36h2a1e443_0
  - pygments=2.7.3=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.17.3=py36h7b6447c_0
  - python=3.6.7=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.6.0=py3.6_cuda9.2.148_cudnn7.6.3_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py36h7b6447c_2
  - pyzmq=20.0.0=py36h2531618_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - scikit-image=0.17.2=py36hdf5156a_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=46.4.0=py36_0
  - six=1.15.0=py36h06a4308_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.9.1=py36_0
  - testpath=0.4.4=py_0
  - tifffile=2021.3.17=pyhd3eb1b0_1
  - tk=8.6.8=hbc83047_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchvision=0.7.0=py36_cu92
  - tornado=6.1=py36h27cfd23_0
  - traitlets=4.3.3=py36_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - cachetools==4.2.0
    - chardet==4.0.0
    - click==7.1.2
    - configparser==5.0.1
    - cycler==0.10.0
    - dlib==19.21.1
    - docker-pycreds==0.4.0
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.12
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.34.0
    - idna==2.10
    - importlib-metadata==3.3.0
    - light-the-torch==0.3.5
    - lmdb==1.0.0
    - markdown==3.3.3
    - matplotlib==3.3.4
    - numpy==1.18.4
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - pillow==7.1.2
    - pip==20.2.4
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt5==5.9.2
    - pytorch-fid==0.2.0
    - pyyaml==5.3.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.4.1
    - sentry-sdk==0.19.5
    - shortuuid==1.0.1
    - sip==4.19.8
    - smmap==3.0.4
    - subprocess32==3.5.4
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.7.0
    - torchsummary==1.5.1
    - tqdm==4.46.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - wandb==0.10.12
    - watchdog==1.0.2
    - werkzeug==1.0.1
